- samples/AspNetCore/WebSample/Startup.cs
- src/AWS.Logger.AspNetCore/AWSLogger.cs
- src/AWS.Logger.AspNetCore/AWSLoggerFactoryExtensions.cs
- src/AWS.Logger.AspNetCore/AWSLoggerProvider.cs
- test/AWS.Logger.AspNetCore.Tests/TestFormatter.cs
Hi Spati2 & Norm & AWS Dev Team,
First of all, thank you for this great library. We just started to use it and it's great.
Although we are missing a functionality. For us, it's very important that we need to be able to customize the messages. For example: we need to have a transaction id injected to every one of our messages, and we want to see the LogLevel as well. This is very important to us, and this can be solved if we can provide our own formatter. Currently, unfortunately that is not possible.
ASP.NET Core (Kestrel, EF etc.) internally uses LogDebug, LogInformation, LogTrace etc. overloads of ILogger where the default formatter is getting applied. We want to format even the ASPNET Core internal logging messages, so in order to achieve this, the Log() overload needs to be customized …
> Added custom formatting possibility

- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
If there's an exception in `AWSLoggerCore` constructor (wrong credentials, AWS not available, etc) then `_cancelStartSource` may stay undefined and break .NET CLR Finalizer thread
> Prevent NRE in finalizer

- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
- src/AWS.Logger.SeriLog/AWSSink.cs
- src/AWS.Logger.SeriLog/Properties/AssemblyInfo.cs
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.SeriLog.Tests/SeriLoggerTestClass.cs
replaced IFormatProvider with ITextFormatter. The implementation is borrowed from Serilog.Sinks.AwsCloudWatch
> Add ITextFormatter to Serilog plugin so can format messages

- src/AWS.Logger.AspNetCore/AWSLogScope.cs
- src/AWS.Logger.AspNetCore/AWSLogger.cs
- src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs
- src/AWS.Logger.AspNetCore/AWSLoggerProvider.cs
- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/NLog.AWS.Logger/AWSTarget.cs
- test/AWS.Logger.AspNetCore.Tests/TestFormatter.cs
- test/AWS.Logger.AspNetCore.Tests/TestScope.cs
*Issue #44 :
- Implemented logic to support ILogger.BeginScope<T>
- Extended configuration with "IncludeScopes" property, as well as
reading the new configuration property
- Implemented test cases
- Some minor code clean-up in the configuration classes (getter and setter for readability) & tests (removed unused namespaces)
> Implemented aws/aws-logging-dotnet#44

- src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs
- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
- src/NLog.AWS.Logger/AWSTarget.cs
- test/AWS.Logger.AspNetCore.Tests/appsettings.json
- test/AWS.Logger.Log4Net.Tests/log4net.config
- test/AWS.Logger.NLog.Tests/Regular.config
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroup.json
- test/AWS.Logger.TestUtils/BaseTestClass.cs
Issue #83 
Added LogStreamPrefix to allow the library user, optionally, to specify a user-defined segment of the log stream prefix. If specified, the log stream name will begin with this user-defined segment, followed by the system-defined prefix segment of the yyyy/mm/dd form, then followed by the suffix (user defined or system defined, as in prior state).
Enhanced unit tests for all supported unit test frameworks to test LogStreamPrefix in a manner similar to the pre-existing LogStreamSuffix.
**The design invariant that a unique date-based component be included in the log stream name is maintained.** 
Backwards compatibility is maintained, as leaving the LogStreamPrefix null or empty results in behavior identical to the prior state.
As per design of the CloudWatch log stream enumeration …
> User-defined log stream prefix (issue #83)

- src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs
- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
- src/NLog.AWS.Logger/AWSTarget.cs
- test/AWS.Logger.AspNetCore.Tests/TestConfigurationBase.cs
- test/AWS.Logger.AspNetCore.Tests/TestDontCreateLogGroup.cs
- test/AWS.Logger.AspNetCore.Tests/TestFilter.cs
- test/AWS.Logger.AspNetCore.Tests/dontCreateLogGroupMissing.json
- test/AWS.Logger.AspNetCore.Tests/dontCreateLogGroupTrue.json
- test/AWS.Logger.UnitTests/DontCreateLogGroupTests.cs
Issue  #98
Added boolean "DontCreateLogGroup" property, to allow developers to switch off auto-creation of log groups. This avoids an API call to [DescribeLogGroups](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogGroups.html) (which is used to determine if the configured Log Group already exists), useful in scenarios where permission to enumerate log groups in the account is not available. 
Default behavior (DontCreateLogGroup == false) matches prior state behavior.
Added wireup for all supported logging frameworks.
Added tests (requiring some form of AWS access, as with many of the other tests), to help confirm, via AWSLoggerCore, that the new setting does indeed prevent auto-creation of log groups.
Added tests to verify that the configuration value …
> add DontCreateLogGroup, to make auto-creation of Log Groups optional

- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
*Issues #73, #20*
Prevent `Monitor` loop to break on http timeout during logs sending. 
> Fixed issue with SendMessages timeout led to Monitor loop break

- README.md
- samples/NLog/ConfigExample/ConfigExample.csproj
- samples/NLog/ConfigExample/NLog.config
- samples/NLog/ConfigExample/packages.config
@normj Fixed NLog-documentation so it will work on new NetCore-projects (autoloading of NLog-extension-assembly not working and needs help using `<extensions>`)
Also updated NLog-sample to have correct NLog-dependency-version.
> Updated NLog config example to work on NetCore

- samples/Log4net/BasicAWSCredentialsConfigurationExample/BasicAWSCredentialsConfigurationExample.csproj
- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.NLog.Tests/AWS.Logger.NLog.Tests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
https://github.com/aws/aws-logging-dotnet/issues/136
Update references to the AWS SDK for .NET to the latest 3.5 version. Since this is a significant version bump I major version bumped all of the packages. Compatible is very high between 3.3. and 3.5 but just to make it obvious that SDK version changed to 3.5 it seemed worth bumping the major version.
> Update version of the AWS SDK for .NET to the latest 3.5 version

- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
* **Issue**  #134
* **Description of changes:** Handle ResourceNotFoundException with refresh of _currentStreamName
> AWSLoggerCore - Handle ResourceNotFoundException with refresh of _currentStreamName

- RELEASE.CHANGELOG.md
- samples/Log4net/BasicAWSCredentialsConfigurationExample/BasicAWSCredentialsConfigurationExample.csproj
- samples/Log4net/ConfigExample/ConfigExample.csproj
- samples/Log4net/ProgrammaticConfigurationExample/ProgrammaticConfigurationExample.csproj
- samples/Log4net/ProgrammaticConfigurationExample/packages.config
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
Update the samples and change log for use version 2.0.10 of log4net. Looks like the assembly version number didn't change for package version 2.0.10 which is why you can see in the old style csproj show 2.0.9 in the assembly version but it is pulling in version 2.0.10.
> Changes to update log4net dependency to version 2.0.10

- src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs
- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
- src/NLog.AWS.Logger/AWSTarget.cs
Issue #118 
This PR adds a new property to disable the Library Log errors (instead of using an empty string)
> Updated library with new property to disable library error logging.

- samples/Log4net/BasicAWSCredentialsConfigurationExample/BasicAWSCredentialsConfigurationExample.csproj
- samples/Log4net/BasicAWSCredentialsConfigurationExample/packages.config
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.NLog.Tests/AWS.Logger.NLog.Tests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
*Issue #, if available:* #160
1. Updates AWS SDK dependencies to v3.7
2. Drops support for .NET Standard 1.5 where we did so, since [AWS SDK no longer supports .NET Standard 1.3](https://aws.amazon.com/blogs/developer/net-standard-1-3-is-no-longer-supported-in-aws-sdk-for-net-version-3-7/). Performed a major version bump.
* Note we had previously done this for AWS.Logger.Log4net in #154 with that security fix
> Update AWS SDK dependencies to 3.7, and finish dropping .NET Standard 1.5 Support

- README.md
New section in the README provides a list of permissions required in IAM in order for the logging to function.
No issue associated.
Description:
Hi, this change simply adds a section to the README file providing a bit of extra guidance on the permissions required for the provided AWS credentials to save the next person from having to hunt down the answer. I found the answer on the AWS blog, and have referenced it in my update.
I confirm that my contribution is made under the terms of the Apache 2.0 license.
> Updated README with IAM permissions required.

- src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs
- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
- src/NLog.AWS.Logger/AWSTarget.cs
*Issue #:* #180 
Add a configurable flush timeout, replacing hard coded 30s.
___
> Add a flush timeout to config and use it instead of hardcoded 30s

- README.md
- src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs
- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
- src/NLog.AWS.Logger/AWSTarget.cs
- test/AWS.Logger.UnitTests/DisableLogGroupCreationTests.cs
Implement retention policy application in the core cloudwatch logger.
Taking another crack based on the changes from @DebashishSaha in this PR https://github.com/aws/aws-logging-dotnet/pull/208 to address @normj's  performance concerns related to performing a blocking application of the retention policy in `LogEventTransmissionSetup`. 
Instead iff a new log group is created _and_ a retention policy is configured to be created, a background task is started which then applies said policy to the newly created group.
> Implementing Retention Policy to Cloudwatch

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
*Description of changes:* Version bump to release #229 and #228 
**Note:** I did not version bump Serilog even though there is an AWS.Logger.Core change. Given the nature of the change (removing unused code), I didn't think it was worth it but let me know if you disagree.
Proposed changelog entries:
```
AWS.Logger.Log4Net
* Correctly honor NewLogGroupRetentionInDays during initialization
NLog.AWS.Logger
* Correctly honor NewLogGroupRetentionInDays during initialization
AWS.Logger.AspNetCore
* Update NullExternalScopeProvider/NullScope handling for newer Microsoft.Extensions.Logging.Abstractions
AWS.Logger.Core
* Remove unused code from old .NET Standard 1.5 target
```
> chore: Version bump

- samples/AspNetCore/ConsoleSample/ConsoleSample.csproj
- samples/AspNetCore/WebSample/Startup.cs
- samples/AspNetCore/WebSample/WebSample.csproj
- samples/Serilog/SerilogTestCode/SerilogTestCode.csproj
- samples/Serilog/SerilogTestCodeFromConfig/SerilogTestCodeFromConfig.csproj
- samples/Serilog/SerilogTestCodeFromConfigRestrictedToMinimumLevel/SerilogTestCodeFromConfigRestrictedToMinimumLevel.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.AspNetCore.Tests/TestClass.cs
- test/AWS.Logger.AspNetCore.Tests/TestFilter.cs
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.NLog.Tests/AWS.Logger.NLog.Tests.csproj
- test/AWS.Logger.NLog.Tests/TestClass.cs
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
- test/AWS.Logger.UnitTests/DisableLogGroupCreationTests.cs
Update tests and samples to use .NET 8 and clean up all warnings in the solutions. I also added the flag to treat warnings as flags to avoid new warnings coming in the future.
Confirmed in Visual Studio solution compiles with no warnings and all tests run successfully.
> Update tests and samples to modern .NET versions and clean up all warnings

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.AspNetCore/AWSLoggerProvider.cs
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/AWS.Logger.SeriLog/AWSSink.cs
- src/NLog.AWS.Logger/AWSTarget.cs
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
SDK-169882
chore: Update User-Agent string
We have 4 separate projects in this repo each serving as a different type of logging provider.
* [AWS.Logger.AspNetCore](https://www.nuget.org/packages/AWS.Logger.AspNetCore)
* [AWS.Logger.NLog](https://www.nuget.org/packages/AWS.Logger.NLog)
* [AWS.Logger.SeriLog](https://www.nuget.org/packages/AWS.Logger.SeriLog)
* [AWS.Logger.Log4net](https://www.nuget.org/packages/AWS.Logger.Log4net)
They all reference [AWS.Logger.Core](https://www.nuget.org/packages/AWS.Logger.Core) and use the `AWSLoggerCore(AWSLoggerConfig config, string logType)` constructor from this package to instantiate the CloudWatch client. Each logging provider passes a different string for the `logType` parameter of the …
> [UA update] chore: Update User-Agent string

- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- test/AWS.Logger.NLog.Tests/AWS.Logger.NLog.Tests.csproj
The `IClientConfig.DetermineServiceURL()` method has been deprecated. Since the project is configured to treat warning as errors, the build fails.
> fix build errors

- .github/workflows/aws-ci.yml
- buildtools/ci.buildspec.yml
DOTNET-7478
* Add AWS CI workflow for running unit and integ tests (I needed to install mono for the tests to run on linux)
> ci: Add AWS CI workflow for running unit and integ tests

- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
Related to issue #244 
Description of issue was replied against main issue https://github.com/aws/aws-logging-dotnet/pull/244#issuecomment-2106242792
With the recent addition of a `LogStreamName` configuration to allow overriding the generated stream name, it was overlooked that the library will throw an exception if that LogStreamName already exists, defeating the purpose of that added feature.
In addition, with the recent CloudWatch improvement of "removing the requirement of providing a sequence token when calling Amazon CloudWatch Logs PutLogEvents API", which this library has implemented, it's probably a good idea to not throw an exeption and crash the monitor if the `LogStreamName` already exists for any configuration. However for backwards compatibility, a …
> Prevent monitor from not starting when LogStreamName already exists

- src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs
- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
- src/NLog.AWS.Logger/AWSTarget.cs
*Issue #, if available:* #255
Exposes `AmazonCloudWatchLogsConfig.AuthenticationRegion` property. Implementing this small change allows users to use the AWS Logger .NET for different regions than just 'us-east-1' with Localstack.
___
> Exposes AmazonCloudWatchLogsConfig.AuthenticationRegion property.

- src/NLog.AWS.Logger/AWSTarget.cs
*Issue #, if available:* https://github.com/aws/aws-logging-dotnet/issues/255
Followup to  #260 where NLog Layout Logic is applied for AuthenticationRegion
> NLog AWSTarget apply Layout logic for AuthenticationRegion

- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
#253, https://github.com/aws/aws-sdk-net/issues/1968, DOTNET-5636
There's a possible deadlock when using:
1. AWS.Logger.Log4net
2. AWSSDK.Core >= 3.7.1 (which introduced a configurable IMDS URI)
3. Either EC2 IMDS credentials or no credentials
I wrote a longer description with stack traces in https://github.com/aws/aws-sdk-net/issues/1968#issuecomment-2121251710, but in summary:
1. The application thread calls `LogManager.GetLogger` to activate our [`AWSAppender`](https://github.com/aws/aws-logging-dotnet/blob/5c0c9ecffc0a8315f8ee5773a54029148bf6cc55/src/AWS.Logger.Log4net/AWSAppender.cs#L15). This gets [this lock](https://github.com/apache/logging-log4net/blob/19fb2d1ccb2132860b65f30b28bab8132a89b875/src/log4net/Core/DefaultRepositorySelector.cs#L274) in log4net's …
> Lazily initialize the internal CloudWatch Logs client to avoid a deadlock when using log4net

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/AWSTarget.cs
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
*Issue #, if available:* N/A
*Description of changes:* Releasing #269 
> Releasing #269

- CONTRIBUTING.md
Update CONTRIBUTION.md to include change files section since the repository now uses AutoVer for versioning and changelog creation.
> chore: update CONTRIBUTION.md to include change files section

- test/AWS.Logger.AspNetCore.Tests/TestClass.cs
- test/AWS.Logger.Log4Net.Tests/MultiThreadBufferFullTest.config
- test/AWS.Logger.Log4Net.Tests/MultiThreadTest.config
- test/AWS.Logger.Log4Net.Tests/OverrideLogStreamName.config
- test/AWS.Logger.Log4Net.Tests/Properties/AssemblyInfo.cs
- test/AWS.Logger.Log4Net.Tests/TestClass.cs
- test/AWS.Logger.Log4Net.Tests/log4net.config
- test/AWS.Logger.NLog.Tests/AWSNLogGroupEventSizeExceededTest.config
- test/AWS.Logger.NLog.Tests/AWSNLogGroupMultiThreadBufferFullTest.config
- test/AWS.Logger.NLog.Tests/AWSNLogGroupMultiThreadTest.config
- test/AWS.Logger.NLog.Tests/AWSNLogOverrideLogStreamName.config
- test/AWS.Logger.NLog.Tests/Regular.config
- test/AWS.Logger.NLog.Tests/TestClass.cs
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroup.json
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroupMultiThreadBufferFullTest.json
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroupMultiThreadTest.json
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroupOverrideLogStreamName.json
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroupRestrictedToMinimumLevel.json
- test/AWS.Logger.SeriLog.Tests/SeriLoggerTestClass.cs
- test/AWS.Logger.TestUtils/BaseTestClass.cs
- test/AWS.Logger.TestUtils/TestFixture.cs
The tests in the release pipeline have been consistently failing due to stability issues. The tests interfere with each other and are not properly set up to run in parallel. Given that the test projects target multiple frameworks, the test runs affect each other even if tests within a certain class run sequentially. This PR applies multiple fixes to the tests to ensure a stable and consistent run.
* Updated log group names to contain unique elements. This was the main issue since several tests publish to a log group with the same name. This affected event count assertions and test cleanup.
* Updated function calls to use async/await
* Updated certain threading calls to more recent versions of those calls. Task.Factory.StartNew -> Task.Run, Thread.Sleep -> …
> fix: fixed issues with test suite instability
