aws/aws-logging-dotnet

- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.dll.nuspec
- src/AWS.Logger.Log4net/Properties/AssemblyInfo.cs
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.FilterTests/Properties/AssemblyInfo.cs
- test/AWS.Logger.Log4Net.FilterTests/TestFilter.cs
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.Log4Net.Tests/Properties/AssemblyInfo.cs
- test/AWS.Logger.Log4Net.Tests/TestClass.cs
attempted to preserve all the magic things done in the csproj's to make the references work :)
> Add .Net Core support for log4net

- src/NLog.AWS.Logger/AWSTarget.cs
Support for LogGroup + Region + Profile + ProfilesLocation + LogStreamNameSuffix
Resolves #47
>  NLog AWSTarget apply Layout logic to config-properties 

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
> Updating csproj to omit generation of .pdb files in release mode

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
https://github.com/aws/aws-logging-dotnet/pull/81#issuecomment-485118975
Adding back PDB files to NuGet packages. 
> Add pdb files back

- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.NLog.Tests/AWS.Logger.NLog.Tests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
* Update reference to Cloudwatch Logs
* Reference SecureToken NuGet package where necessary so that tests can run using AssumeRole credentials.
> Update cloudwatch logs

- README.md
Add information on how to use Serilog with AWS through a config file and code
> Serilog README

- README.md
- RELEASE.CHANGELOG.md
- samples/Serilog/SerilogTestCode/Program.cs
- samples/Serilog/SerilogTestCode/SerilogTestCode.csproj
- samples/Serilog/SerilogTestCodeFromConfig/Program.cs
- samples/Serilog/SerilogTestCodeFromConfig/SerilogTestCodeFromConfig.csproj
- samples/Serilog/SerilogTestCodeFromConfig/appsettings.json
I added sample code for Serilog to the samples directory. 
SerilogTestCode uses code configuration for the logger and SerilogTestCodeFromConfig uses a config file (appsettings.json) to configure the logger
> added samples for Serilog with code config and file config

- src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs
- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
- src/NLog.AWS.Logger/AWSTarget.cs
Added support for using ServiceUrl. Resolving #93
> AWSLoggerConfig - Added ServiceUrl for support of LocalStack

- .github/workflows/stale_issues.yml
> chore: update timing for stale/ancient

- .github/workflows/stale_issues.yml
* **Description of changes:** Fix typo on `stale_issues` workflow
> Fix typo on stale_issues workflow

- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/NLog.AWS.Logger/AWSTarget.cs
> fix: wriiten typo

- samples/Log4net/BasicAWSCredentialsConfigurationExample/BasicAWSCredentialsConfigurationExample.csproj
- samples/Log4net/BasicAWSCredentialsConfigurationExample/packages.config
- samples/Log4net/ConfigExample/ConfigExample.csproj
- samples/Log4net/ConfigExample/packages.config
- samples/Log4net/ProgrammaticConfigurationExample/ProgrammaticConfigurationExample.csproj
- samples/Log4net/ProgrammaticConfigurationExample/packages.config
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
*Issue #:* https://github.com/aws/aws-logging-dotnet/issues/162
Changes to update log4net dependency to version 2.0.12
___
> Changes to update log4net dependency to version 2.0.12

- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
*Issue #:* #164 
Added support for restrictedToMinimumLevel to Serilog.
---
> Added support for restrictedToMinimumLevel to Serilog.

- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
> Add missing parameter text.

- src/AWS.Logger.Core/Core/IAWSLoggerCore.cs
> Add missing parameter description.

- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
> Add documentation.

- samples/Log4net/BasicAWSCredentialsConfigurationExample/BasicAWSCredentialsConfigurationExample.csproj
- samples/Log4net/BasicAWSCredentialsConfigurationExample/packages.config
- samples/Log4net/ConfigExample/ConfigExample.csproj
- samples/Log4net/ConfigExample/packages.config
- samples/Log4net/ProgrammaticConfigurationExample/ProgrammaticConfigurationExample.csproj
- samples/Log4net/ProgrammaticConfigurationExample/packages.config
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
*Issue #, if available:* #214
Changes to update log4net dependency to version 2.0.15
___
> Changes to update log4net dependency to version 2.0.15

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
Version bump commit to release PR https://github.com/aws/aws-logging-dotnet/pull/224
> chore: version bump commit

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
*Issue #, if available:* N/A
*Description of changes:* Packs the READMEs for display on NuGet.org, see https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/
> chore: Adding package READMEs

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.AspNetCore/AWSLoggerProvider.cs
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/AWS.Logger.SeriLog/AWSSink.cs
- src/NLog.AWS.Logger/AWSTarget.cs
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
> [Merge dev -> main] chore: Update User-Agent string (#247)

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.AspNetCore/AWSLoggerProvider.cs
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/AWS.Logger.SeriLog/AWSSink.cs
- src/NLog.AWS.Logger/AWSTarget.cs
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.NLog.Tests/AWS.Logger.NLog.Tests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
> Merge dev -> master

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
Version bump packages to release log stream name fix.
> Version bump logging packages

- .github/workflows/aws-ci.yml
- buildtools/ci.buildspec.yml
- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.AspNetCore/AWSLoggerConfigSection.cs
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Core/AWSLoggerConfig.cs
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/AWS.Logger.SeriLog/AWSLoggerSeriLogExtension.cs
- src/NLog.AWS.Logger/AWSTarget.cs
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
> ci: Add AWS CI workflow for running unit and integ tests

- RELEASE.CHANGELOG.md
Fix typo in release.changelog.md
> Fix typo in release.changelog.md

- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
*Issue #, if available:* #263
Version bump `AWS.Logger.NLog`
> Version bump AWS.Logger.NLog

- RELEASE.CHANGELOG.md
- src/NLog.AWS.Logger/AWSTarget.cs
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
> Sync Dev To Master

- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Core/IAWSLoggerConfig.cs
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.Log4net/AWSAppender.cs
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/AWSTarget.cs
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
*Issue #, if available:* N/A
1. Version bump to release #269 
2. Follow-up to #248, clarifies that docstring in a few more places
> Version bump to release #269

- RELEASE.CHANGELOG.md
> chore: Update RELEASE.CHANGELOG.md

- CONTRIBUTING.md
> Merge `master` into `dev`

- .github/workflows/aws-ci.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/sync-main-dev.yml
DOTNET-7758
This PR updates config files to support GitHub CI for V4 SDK
> chore: update config files to support GitHub CI for V4

- .autover/changes/f2cd4eda-bee4-4d41-9170-f8fdbe497a13.json
- samples/AspNetCore/ConsoleSample/ConsoleSample.csproj
- samples/Serilog/SerilogTestCodeFromConfig/SerilogTestCodeFromConfig.csproj
- samples/Serilog/SerilogTestCodeFromConfigRestrictedToMinimumLevel/SerilogTestCodeFromConfigRestrictedToMinimumLevel.csproj
- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
This PR updates package dependencies to address the security vulnerability in `System.Text.Json` 8.0.0
> fix: Update dependencies to address security vulnerabilities

- .autover/autover.json
- .autover/changes/f2cd4eda-bee4-4d41-9170-f8fdbe497a13.json
- CHANGELOG.md
- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
Reverts aws/aws-logging-dotnet#287
> Revert "Release 2024-12-11"

- .autover/autover.json
- .autover/changes/f2cd4eda-bee4-4d41-9170-f8fdbe497a13.json
- CHANGELOG.md
- src/AWS.Logger.AspNetCore/AWS.Logger.AspNetCore.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Log4net/AWS.Logger.Log4net.csproj
- src/AWS.Logger.SeriLog/AWS.Logger.SeriLog.csproj
- src/NLog.AWS.Logger/NLog.AWS.Logger.csproj
This reverts commit fe085e9dfa7a125db51b6d119efc4a7239fb7aff in `master`
> Revert "Release 2024-12-11 (#287)"

- CHANGELOG.md
- test/AWS.Logger.AspNetCore.Tests/TestClass.cs
- test/AWS.Logger.Log4Net.Tests/MultiThreadBufferFullTest.config
- test/AWS.Logger.Log4Net.Tests/MultiThreadTest.config
- test/AWS.Logger.Log4Net.Tests/OverrideLogStreamName.config
- test/AWS.Logger.Log4Net.Tests/Properties/AssemblyInfo.cs
- test/AWS.Logger.Log4Net.Tests/TestClass.cs
- test/AWS.Logger.Log4Net.Tests/log4net.config
- test/AWS.Logger.NLog.Tests/AWSNLogGroupEventSizeExceededTest.config
- test/AWS.Logger.NLog.Tests/AWSNLogGroupMultiThreadBufferFullTest.config
- test/AWS.Logger.NLog.Tests/AWSNLogGroupMultiThreadTest.config
- test/AWS.Logger.NLog.Tests/AWSNLogOverrideLogStreamName.config
- test/AWS.Logger.NLog.Tests/Regular.config
- test/AWS.Logger.NLog.Tests/TestClass.cs
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroup.json
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroupMultiThreadBufferFullTest.json
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroupMultiThreadTest.json
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroupOverrideLogStreamName.json
- test/AWS.Logger.SeriLog.Tests/AWSSeriLogGroupRestrictedToMinimumLevel.json
- test/AWS.Logger.SeriLog.Tests/SeriLoggerTestClass.cs
- test/AWS.Logger.TestUtils/BaseTestClass.cs
- test/AWS.Logger.TestUtils/TestFixture.cs
> Fix dev and master sync up

- .autover/changes/89baf7c9-a895-47ef-a406-839f4826c24c.json
- samples/Log4net/BasicAWSCredentialsConfigurationExample/BasicAWSCredentialsConfigurationExample.csproj
- samples/Serilog/SerilogTestCode/SerilogTestCode.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.NLog.Tests/AWS.Logger.NLog.Tests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
DOTNET-7990
Update .NET SDK dependencies to v4.0.0-preview8
> chore: Update .NET SDK dependencies to v4.0.0-preview.8

- .autover/changes/263a5c38-9f7f-404d-a79c-33337a095a82.json
- samples/AspNetCore/ConsoleSample/ConsoleSample.csproj
- samples/Log4net/BasicAWSCredentialsConfigurationExample/BasicAWSCredentialsConfigurationExample.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- src/AWS.Logger.Core/Core/AWSLoggerCore.cs
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.NLog.Tests/AWS.Logger.NLog.Tests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
DOTNET-8029
Update AWS SDK to Preview 11
> Update AWS SDK to Preview 11

- .autover/changes/dd9ab37e-81b5-4984-9577-8ef011b79926.json
- samples/AspNetCore/ConsoleSample/ConsoleSample.csproj
- samples/Log4net/BasicAWSCredentialsConfigurationExample/BasicAWSCredentialsConfigurationExample.csproj
- samples/Serilog/SerilogTestCode/SerilogTestCode.csproj
- samples/Serilog/SerilogTestCodeFromConfig/SerilogTestCodeFromConfig.csproj
- samples/Serilog/SerilogTestCodeFromConfigRestrictedToMinimumLevel/SerilogTestCodeFromConfigRestrictedToMinimumLevel.csproj
- src/AWS.Logger.Core/AWS.Logger.Core.csproj
- test/AWS.Logger.AspNetCore.Tests/AWS.Logger.AspNetCore.Tests.csproj
- test/AWS.Logger.Log4Net.FilterTests/AWS.Logger.Log4Net.FilterTests.csproj
- test/AWS.Logger.Log4Net.Tests/AWS.Logger.Log4Net.Tests.csproj
- test/AWS.Logger.NLog.FilterTests/AWS.Logger.NLog.FilterTests.csproj
- test/AWS.Logger.NLog.Tests/AWS.Logger.NLog.Tests.csproj
- test/AWS.Logger.SeriLog.Tests/AWS.Logger.SeriLog.Tests.csproj
- test/AWS.Logger.TestUtils/AWS.Logger.TestUtils.csproj
- test/AWS.Logger.UnitTests/AWS.Logger.UnitTests.csproj
> chore: update .NET SDK to v4.0.0

- samples/Serilog/SerilogTestCode/SerilogTestCode.csproj
- samples/Serilog/SerilogTestCodeFromConfig/SerilogTestCodeFromConfig.csproj
- samples/Serilog/SerilogTestCodeFromConfigRestrictedToMinimumLevel/SerilogTestCodeFromConfigRestrictedToMinimumLevel.csproj
Fix incorrect package reference. Moved to a project reference.
> fix wrong package reference

- samples/Serilog/SerilogTestCode/SerilogTestCode.csproj
- samples/Serilog/SerilogTestCodeFromConfig/SerilogTestCodeFromConfig.csproj
- samples/Serilog/SerilogTestCodeFromConfigRestrictedToMinimumLevel/SerilogTestCodeFromConfigRestrictedToMinimumLevel.csproj
> Merge dev into main

- .github/dependabot.yml
- .github/workflows/handle-stale-discussions.yml
- .github/workflows/semgrep-analysis.yml
> Sync main from dev

- samples/NLog/ProgrammaticConfigurationExample/ProgrammaticConfigurationExample.csproj
> Remove out of date packagerefence (#338)
